### PR TITLE
Add UI to manage plugins

### PR DESCRIPTION
**Pull request by stas-demydiuk**
UI allows to see the list of all available plugins, marks installed ones and allow to install/update particular plugin

image

### CODE REVIEW

**Comment by ycahome** [comment]
this is a totally different approach. i don;t think that i can support versioning at that code base. I think that we should add it as a parallel fork (different plugin).

**Comment by stas-demydiuk** [comment]
Ok, I'll create separate repo then

**Comment by ycahome** [comment]
What if we create a common repository for python plugin list of sources.

This could easily used by mine or your version and any other version in the future.

 

Also, I believe that developers need to add this to core Domoticz sources.

**Comment by stas-demydiuk** [comment]
Yes, it is really good idea to share plugins data. I'm just a bit worried about setup process as currently it is just required to clone repository to setup plugins and additional repo will add external dependency. Do you have any ideas how we can handle that?

**Pull request closed without merging**
