### PR TITLE
Validate plugin repos exist

### PR DESCRIPTION
**Pull request by galadril**

### CODE REVIEW

**Comment by galadril** [comment]
@ycahome can you validate/merge plz?

**Comment by galadril** [comment]
I noticed that like 7 plugin repositories where giving 404's as they were not existing anymore, so i created this issue to add a GitHub Workflow to parse the plugin data and actually validate if the plugin repos still exist

#54 
 
 
image


I've cleaned not existing plugins from the list

**Comment by galadril** [comment]
Validate the existings of the repos on PR/commit #54

**Review by ycahome — APPROVED** [review]
Added AWTRIX3 Plugin

**Review by ycahome — APPROVED** [review]
Added E-Flux Plugin

**Review by ycahome — APPROVED** [review]

**Comment by ycahome** [comment]
There are multiple changes that cannot track. Can you please create a solid pull request with a single commit for each file?

**Review by ycahome — CHANGES_REQUESTED** [review]
There are multiple changes that cannot track. Can you please create a solid pull request with a single commit for each file?

**Comment by galadril** [comment]
Ive made this PR to be only about validating if the repos actually exist
This action/workflow is going to run on PR's so that when a new PR is created, all repo urls are being validated

**Comment by galadril** [comment]
Ill make another one with the 2 new plugins when this is merged. to align the plugin id's ;)

**Pull request closed without merging**
